controller_manager:
  ros__parameters:
    update_rate: 50  # Hz # 100

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster
    
    joint_trajectory_position_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    steering_controller:
      type: position_controllers/JointGroupPositionController

    velocity_controllers:
      type: velocity_controllers/JointGroupVelocityController

    effort_controllers:
      type: effort_controllers/JointGroupEffortController

steering_controller:
  ros__parameters:
    joints:
      - front_wheel_joint
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity

# velocity_controllers:
#   ros__parameters:
#     joints: 
#       - rear_left_wheel_joint
#       - rear_right_wheel_joint
#     interface_name: velocity
#     command_interfaces:
#       - velocity
#     state_interfaces:
#       - position
#       - velocity

effort_controllers:
  ros__parameters:
    joints: 
      - rear_left_wheel_joint
      - rear_right_wheel_joint
    command_interfaces:
      - effort
    state_interfaces:
      - position
      - velocity
      - effort


forward_position_controller:
  ros__parameters:
    joints:
      - joint_1
      - joint_2
      - joint_3
    interface_name: position


joint_trajectory_position_controller:
  ros__parameters:
    joints:
      - joint_1
      - joint_2
      - joint_3

    command_interfaces:
      - position

    state_interfaces:
      - position
      - velocity

    state_publish_rate: 50.0 # Defaults to 50
    action_monitor_rate: 20.0 # Defaults to 20

    allow_partial_joints_goal: false # Defaults to false
    open_loop_control: true
    allow_integration_in_goal_trajectories: true
    constraints:
      stopped_velocity_tolerance: 0.01 # Defaults to 0.01
      goal_time: 0.0 # Defaults to 0.0 (start immediately)
